[build-system]
requires = ["hatchling>=1.27", "hatch-vcs>=0.4", "packaging"]
build-backend = "hatch.backend"
backend-path = ["."]

[project]
name = "dxgb-bench"
dynamic = ["version"]
requires-python = ">=3.12"
description="Benchmarking scripts for XGBoost."
readme = { file = "README.md", content-type = "text/markdown" }

dependencies = [
    "numpy",
    "pandas",
    "pyarrow",
    "tqdm",
    "pyhwloc",
    "packaging",
    "scipy",
    "scikit-learn",
    "typing_extensions",
    "xgboost>=3.0",
]

[project.scripts]
dxgb-bench = "dxgb_bench.dxgb_bench:cli_main"
dxgb-dist-bench = "dxgb_bench.dxgb_dist_bench:cli_main"
dxgb-datasets = "dxgb_bench.datasets.public.cli:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build]
exclude = ["*.so", "*.dll", "*.dylib", "*.lib", "*.exp", "*.pdb", "__pycache__"]

[tool.hatch.build.targets.sdist]
include = ["/dxgb_bench", "/hatch", "/pyproject.toml", "/README.md", "/LICENSE"]

[tool.hatch.build.targets.wheel]
packages = ["dxgb_bench"]
exclude = ["*.cc", "*.cu", "*.hpp", "CMakeLists.txt", "*.so", "*.dll", "*.dylib", "*.lib", "*.exp", "*.pdb", "__pycache__"]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "hatch/hook.py"

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
follow_imports = "silent"

[tool.ruff.lint]
select = ["I"]
