Some simple scripts for running xgboost-dask pipeline.  Heavily inspired by [[https://github.com/NVIDIA/gbm-bench][gbm-bench]] .
By default these scripts use ~dask_cudf~ as bank-end for manipulating datasets.

* Available datasets:
  - mortgage
  - taxi yellow tripdata 2014-01  (Copied from rapids' demo)
  - higgs
  - YearPrediction

* Available algorithms:
  - GPU Histogram
  - CPU Histogram
  - CPU Approx

* Usage
#+BEGIN_SRC bash
python main.py --algo='xgboost-dask-gpu-hist' --data='mortgage' --backend='dask_cudf'
#+END_SRC

The result is saved into a JSON file along with packages' version.  Each run will try to
avoid overwriting previous saved file, so one can run it multiple times without renaming
output file at each run.

* Dependencies
  - XGBoost
  - CUDA
  - cuDF
  - dask[complete]  # pandas, distributed are implicitly included
  - dask_cudf
  - dask_cuda
  - dask_ml  # right now this is not used as there are still some glitches in the pipeline.
  - cupy

#  LocalWords:  LocalWords tripdata XGBoost CUDA cuDF
