name: dxgb_bench

on: [push]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Format and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install packages
      run: |
        python3 -m pip install black isort
    - name: Run lint
      run: |
        black --check .
        isort --profile=black --check .

  tests:
    name: Run basic tests
    env:
      CONDA_OVERRIDE_CUDA: "13.2"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: prefix-dev/setup-pixi@v0.9.5
      with:
        pixi-version: v0.77.0
        environments: dev
    - name: System dependencies
      run: |
        sudo apt install numactl -y
    - name: Install XGBoost
      run: |
        pixi run --environment dev pip install xgboost
    - name: Build
      run: |
        pixi run --environment dev build
        pixi run --environment dev dxgb-bench --version
    - name: Test
      run: |
        pixi run --environment dev pytest -s -v ./tests/*.py
